name: Deploy website plan
on:
  pull_request:
    branches:
      - main
    paths:
      - website/*
jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      TF_VAR_S3_STATE_BUCKET: ${{ secrets.S3_STATE_BUCKET_NAME }}
      TF_VAR_STATE_FILE: ${{ secrets.STATE_FILE }}
      TF_VAR_SITE_BUCKET: ${{ secrets.SITE_BUCKET_NAME }}
      TF_VAR_AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_VAR_DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
      TF_IN_AUTOMATION: "True"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2 

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialise Terraform
        run: |
          cd terraform
          terraform init -backend-config="bucket=${{ secrets.S3_STATE_BUCKET }}"
          terraform plan
      
      - name: Run terraform plan
        id: plan
        run: |
          cd terraform
          echo 'plan<<EOF' >> $GITHUB_OUTPUT
          terraform plan -no-color -out=tfplan >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Comment Plan
        id: comment-plan
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Terraform Plan:
            ```
            ${{ steps.plan.outputs.plan }}
            ```
            Merge this PR to apply these changes.